apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: customer
          image: pirabanjan/buy-it-product-service:my-tag1  # Replace with your image and tag
          ports:
            - containerPort: 8002
          # Add volume mounts and resources as needed
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"  # Adjust the CPU limit as needed
            requests:
              cpu: "100m"  # Adjust the CPU request as needed
  
