name: Trivy scan
on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true

jobs:
  Trviy-scan:
    name: trivy-scan
    runs-on: ubuntu-20.04
    steps:
      - name: Build an image from Dockerfile
        run: |
          pirabanjan/buy-it-customer-service:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'pirabanjan/buy-it-customer-service:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
